package citi.hibernate.entity;
// Generated Aug 7, 2017 6:09:37 PM by Hibernate Tools 5.0.6.Final

/**
 * Own generated by hbm2java
 */
public class Own implements java.io.Serializable {

	private int ownId;
	private Portfolio portfolio;
	private String sticker;

	public Own() {
	}

	public Own(int ownId) {
		this.ownId = ownId;
	}

	public Own(int ownId, Portfolio portfolio, String sticker) {
		this.ownId = ownId;
		this.portfolio = portfolio;
		this.sticker = sticker;
	}

	public int getOwnId() {
		return this.ownId;
	}

	public void setOwnId(int ownId) {
		this.ownId = ownId;
	}

	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	public String getSticker() {
		return this.sticker;
	}

	public void setSticker(String sticker) {
		this.sticker = sticker;
	}

}
