package citi.hibernate.entity;
// Generated Aug 5, 2017 4:22:06 PM by Hibernate Tools 5.0.6.Final

/**
 * Portfolio generated by hbm2java
 */
public class Portfolio implements java.io.Serializable {

	private Integer portfolioId;
	private User user;
	private String portfolioname;
	private String ticker;

	public Portfolio() {
	}

	public Portfolio(User user, String portfolioname, String ticker) {
		this.user = user;
		this.portfolioname = portfolioname;
		this.ticker = ticker;
	}

	public Integer getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(Integer portfolioId) {
		this.portfolioId = portfolioId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPortfolioname() {
		return this.portfolioname;
	}

	public void setPortfolioname(String portfolioname) {
		this.portfolioname = portfolioname;
	}

	public String getTicker() {
		return this.ticker;
	}

	public void setTicker(String ticker) {
		this.ticker = ticker;
	}

}
