package citi.hibernate.entity;
// Generated Aug 7, 2017 6:09:37 PM by Hibernate Tools 5.0.6.Final

/**
 * Record generated by hbm2java
 */
public class Record implements java.io.Serializable {

	private Integer recordId;
	private String ticker;
	private String date;
	private String time;
	private Double open;
	private Double high;
	private Double low;
	private Double close;
	private Integer volume;

	public Record() {
	}

	public Record(String ticker, String date, String time, Double open, Double high, Double low, Double close,
			Integer volume) {
		this.ticker = ticker;
		this.date = date;
		this.time = time;
		this.open = open;
		this.high = high;
		this.low = low;
		this.close = close;
		this.volume = volume;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public String getTicker() {
		return this.ticker;
	}

	public void setTicker(String ticker) {
		this.ticker = ticker;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Double getOpen() {
		return this.open;
	}

	public void setOpen(Double open) {
		this.open = open;
	}

	public Double getHigh() {
		return this.high;
	}

	public void setHigh(Double high) {
		this.high = high;
	}

	public Double getLow() {
		return this.low;
	}

	public void setLow(Double low) {
		this.low = low;
	}

	public Double getClose() {
		return this.close;
	}

	public void setClose(Double close) {
		this.close = close;
	}

	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

}
