package citi.hibernate.entity;
// Generated Aug 9, 2017 1:27:15 PM by Hibernate Tools 5.0.6.Final

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer stockId;
	private Portfolio portfolio;
	private String stockTicker;

	public Stock() {
	}

	public Stock(Portfolio portfolio, String stockTicker) {
		this.portfolio = portfolio;
		this.stockTicker = stockTicker;
	}

	public Integer getStockId() {
		return this.stockId;
	}

	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}

	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	public String getStockTicker() {
		return this.stockTicker;
	}

	public void setStockTicker(String stockTicker) {
		this.stockTicker = stockTicker;
	}

}
