package citi.hibernate.entity;
// Generated Aug 9, 2017 1:27:15 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private Set portfolios = new HashSet(0);

	public User() {
	}

	public User(String username, String password, Set portfolios) {
		this.username = username;
		this.password = password;
		this.portfolios = portfolios;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getPortfolios() {
		return this.portfolios;
	}

	public void setPortfolios(Set portfolios) {
		this.portfolios = portfolios;
	}

}
